version: "3.9"

services:
  user-db:
    image: postgres:latest
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    container_name: user-db
    ports:
      - 54321:5432
    networks:
      - user-default
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user_test
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  user-default:
    external: true
