name: User

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: user
          POSTGRES_DB: user_test
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 54321:5432

    steps:
      - name: checkout project
        uses: actions/checkout@v3

      - name: go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
          check-latest: true

      - name: go mod tidy
        run: go mod tidy

      - name: lint
        uses: golangci/golangci-lint-action@v3

      - name: test
        run: go test ./... -race -count=1 -cover
